/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class trikita_obsqr_Zbar */

#ifndef _Included_combustiblelemons_obsqr_Zbar
#define _Included_combustiblelemons_obsqr_Zbar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     combustiblelemos_obsqr_Zbar
 * Method:    process
 * Signature: (II[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_combustiblelemons_obsqr_Zbar_process
  (JNIEnv *, jobject, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
